### ISSUE TITLE
widget theme

### ISSUE THREAD

**Issue by m-rau** [plan-net/core4#37]
Implement communication between widget/app and widget manager for theming.

**Comment by m-rau** [comment]
to be considered in #58, #56

**Comment by marekmru** [comment]
https://bi.plan-net.com/cdn/assets/js/vue-assets.js
* axios 0.18.x
* vue 2.6.x
* vuetify 1.5.x

https://bi.plan-net.com/cdn/assets/css/vuetify.js

**Comment by marekmru** [comment]
git cdn

**Comment by LuitpoldStotzem** [comment]
The handling of the themes is built in for vue widgets. In the course of extending the Vue widgets I also directly increased and tested the version of Vuetify. 
Attached to this comment is a template which shows the minimum requirements for a working Vue widget
On the CDN I also created and deployed the files suitable for vuetify 2
[VueWidget_Template.txt](https://github.com/plan-net/core4/files/3621905/VueWidget_Template.txt)

**Comment by LuitpoldStotzem** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Download</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://bi.plan-net.com/cdn/assets/css/vuetify_2.0.css" rel="stylesheet">
    <style>
    </style>
</head>
<body>
<div id="app">
    <v-app >
      <v-container>
        <v-btn color="primary"></v-btn>
      </v-container>
    </v-app>
</div>
<script src="https://bi.plan-net.com/cdn/assets/js/vue-assets_2.0.js"></script>
<script>
  new Vue({
    delimiters: ['[[', ']]'],
    el: '#app',
    vuetify: new Vuetify({
      theme: {
        themes: {
          light: window.PNBI_THEME,
          dark: window.PNBI_THEME
        },
      },
    }),
    data: {
    },
    created() {
    },
    methods: {
    }
  })
</script>
</body>
</html>
`

**Comment by marekmru** [comment]
Summary by @LuitpoldStotzem :

The core4OS widget manager offers the function of a "dark mode". In this mode, the automatic setting of CSS classes sets the color representation of the application to light or dark. However, since widgets are individual in nature, when creating a widget the developer must ensure that the widget behaves correctly when the mode is changed.
The widget manager sets the class 'theme--dark' or 'theme--light' depending on the 'dark' parameter, which can be found in the URL when 'dark mode' is activated. The second is the default. The developer has the task to adapt background colors and text colors as well as all other contents displayed within the widget to the respective mode. The following code examples describe the procedure.

**Comment by marekmru** [comment]
theme: {
      dark: true,
      options: {
        customProperties: true
      },
      themes: {
        light,
        dark
      }
    }
